[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@smartcontractkit/chainlink-evm/contracts/=lib/chainlink-evm/contracts',
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
